language: objective-c

env:
  matrix:
    - CONDA_PY=35

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build
      conda config --set show_channel_urls true
      conda config --add channels conda-forge

      conda info
      conda list
      cat /Users/travis/.condarc
      

script:
  - conda build ./recipe
